[project]
authors = ["Nate"]
entry = "main.sw"
license = "Apache-2.0"
name = "cover_product"

[dependencies]
registry_abi = { path = "../abis/registry_abi" }
cover_product_abi = { path = "../abis/cover_product_abi" }
