[project]
authors = ["Nate"]
entry = "main.sw"
license = "Apache-2.0"
name = "bonds-registry"

[dependencies]
token_abi = { path = "../abi/token_abi" }
bond_registry_abi = { path = "../abi/bond_registry_abi" }
