[project]
authors = ["Nate"]
entry = "main.sw"
license = "Apache-2.0"
name = "cover_payment_manager"

[dependencies]
token_abi = { path = "../abis/token_abi" }
executor_abi = { path = "../abis/executor_abi" }
registry_abi = { path = "../abis/registry_abi" }
cpm_abi = { path = "../abis/cpm_abi" }
cover_points_abi = { path = "../abis/cover_points_abi" }
premium_pool_abi = { path = "../abis/premium_pool_abi" }
reentrancy = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.8.0" }
